name: gameserver-app

services:
  app:
    build: .
    ports:
      - 8090:8090
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/leaderboard

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: leaderboard
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: